# Generated by Django 4.1.4 on 2022-12-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeryApp', '0002_products_delete_imagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('help', models.TextField(max_length=300)),
            ],
        ),
    ]
