# Generated by Django 4.1.4 on 2022-12-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeryApp', '0003_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='contact',
            field=models.CharField(max_length=12),
        ),
    ]
